return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "c",
            "lua",
            "vim",
            "vimdoc",
            "query",
            "markdown",
            "markdown_inline",
            "python",
            "go",
            "cmake",
            "make",
            "proto",
            "terraform",
            "yaml",
            "vue",
            "astro",
            "json5",
            "json",
            "jsonc",
            "luadoc",
            "regex",
            "tsx",
            "diff",
            "jsdoc",
            "toml",
            "vim",
            "xml",
            "bash",
            "javascript",
            "typescript",
            "csv",
            "dockerfile",
            "gosum",
            "gotmpl",
            "gomod",
            "gowork",
            "hcl",
            "helm",
            "html",
            "http",
        },
        auto_install = true,
        highlight = {
            enable = true,
        },
    },
}
